### ISSUE TITLE
unable to get response

### ISSUE THREAD

**Issue by tgoldenberg** [hoxxep/Gookie#3]
So I have the `gookie.js` file running on port 8001, but when I test my IP:port in the browser I don't get anything. The webhook as well does not work. I know `ngrok` was mentioned, but any explanation as to why this doesn't work? I'm also a little confused as to how to get `ngrok` to solve this particular problem. Thank you!

**Comment by tgoldenberg** [comment]
Also, everytime the webhook hits the gookie server, it asks for my passphrase for the id_rsa key. How to make this automatic?

**Comment by hoxxep** [comment]
A reason you are unable to access gookie via `http://ip:port` in the browser could be because port forwarding is not set up on your router. Using ngrok tunnels the connection, binding the ngrok's IP to your local machines `ip:port`, and removing the need for your router to forward your public `ip:port` to your local `ip:port`.

As for asking for the passphrase when trying to pull from github during the deploy step, a typical method round this is to use an SSH key which is not protected by a passphrase, or to remove the passphrase on your current key. Or you can use [keychain on Mac](http://insparrow.co.uk/post/85405341789/how-to-use-password-protected-ssh-keys-in-cron) (or the equivalent for your OS, if one exists) to enter the passphrase for you.

**Comment by tgoldenberg** [comment]
So, I needed to add an endpoint to my Azure VM for the Gookie port to be accepted. And as for the ssl, I followed some advice in SO using `eval` that worked fine. Thanks!
